FROM ubuntu:22.04
RUN apt update
RUN apt upgrade -y
RUN apt install -y python3 python3-pip
RUN pip3 install zapv2 requests pprint

RUN mkdir /scanner
RUN mkdir /results
WORKDIR /scanner

COPY . .

ENTRYPOINT ["/usr/bin/python3","/scanner/zap_scanner.py"]